name: Test Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 2,6'

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-liner script
      run: echo "Hello, world!"
