name: Run Maple Event Notice

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 3,6'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        pip install nbconvert pandas numpy
        pip install jupyter

    - name: Install Jupyter Kernel
      run: |
        python -m ipykernel install --user --name=python3

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace mapleEventNotice.ipynb
