name: Run Maple Event Noticce

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 3,6'  # 毎週水曜日と土曜日の0時に実行

jobs:
  install_and_run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # 正しいバージョンに変更

      - name: Install requests module
        run: |
          python -m pip install --upgrade pip
          pip install requests  # requestsをインストール

      - name: Convert Notebook to Python script
        run: |
          jupyter nbconvert --to script --output scripts/mapleEventNotice mapleEventNotice.ipynb

      - name: Run the script
        run: |
          python scripts/mapleEventNotice.py
