name: Run Maple Event Notice

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 3,6'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        pip install nbconvert pandas numpy

    - name: Create scripts directory
      run: |
        mkdir -p scripts

    - name: Convert notebook to Python script
      run: |
        jupyter nbconvert --to script --output scripts/mapleEventNotice mapleEventNotice.ipynb

    - name: List files in scripts directory
      run: |
        ls -l scripts/

    - name: Run Python script
      run: |
        python scripts/mapleEventNotice.py
